---
title: "waffle"
format: html
editor: visual
---

## Waffle Charts

package

```{r}
install.packages("waffle")
```

```{r}
# install.packages("waffle", repos = "https://cinc.rud.is")
library(waffle)

# Vector
x <- c(G1 = 30, G2 = 25, G3 = 20, G4 = 5)

# Waffle chart
waffle(x, rows = 8,
       colors = c("#FFEDA0", "#FEB24C", "#FC4E2A", "#BD0026")) 

```

**Legend position**

The legend position can be changed with `legend_pos` argument. Possible values are `"right"` (default), `"bottom"`, `"left"`, `"top"` and `"none"` to remove the legend.

```{r}
# install.packages("waffle", repos = "https://cinc.rud.is")
library(waffle)

# Vector
x <- c(G1 = 30,  G2 = 25, G3 = 20, G4 = 7, G5 = 5)

# Waffle chart
waffle(x, rows = 6,
       legend_pos = "bottom",
       colors = c("#80DEEAFF","#4DD0E1FF", "#006064FF", "#1531ff", "#a54089")) 

```

Combine waffle charts

```{r}
#install.packages("waffle", repos = "https://cinc.rud.is")
library(waffle)

w1 <- waffle(c(A = 3, B = 10, C = 7, D = 12, E = 6), rows = 5, keep = FALSE, colors = c("#80DEEAFF", "#4DD0E1FF", "#006064FF", "#1531ff", "#a54089", "yellow"))
w2 <- waffle(c(A = 10, B = 20, C = 5, D = 17, E = 8, F = 12), rows = 5, keep = FALSE, colors = c("#80DEEAFF", "#4DD0E1FF", "#006064FF", "#1531ff", "#a54089", "yellow"))

iron(w1, w2)

```

```{r}
# Data
library(ggplot2)
library(waffle)

df <- data.frame(group = LETTERS[1:3],
                 value = c(25, 20, 35))

# Waffle plot
ggplot(df, aes(color = group, values = value)) +
  geom_waffle(n_rows = 8, size = 0.33, colour = "white") +
  scale_color_manual(name = NULL,
                     values = c("#BA182A", "#FF8288", "#FFDBDD"),
                     labels = c("A", "B", "C")) +
  coord_equal() +
  theme_void()


```
