---
title: "Adding points to box plots in R"
format: html
editor: visual
---

# **Adding points to box plots in R**

```{r}
library(paletteer)
library(readxl)
library(tidyverse)
```

## sample dataset

```{r}
# Sample dataset
set.seed(3)
df <- data.frame(x = rexp(100),
                 group = sample(paste("Group", 1:3),
                                size = 100,
                                replace = TRUE))
df
```

Vertical box plot

```{r}
# Vertical box plot
boxplot(df$x, col = "white")

# Points
stripchart(df$x,              # Data
           method = "jitter", # Random noise
           pch = 19,          # Pch symbols
           col = 4,           # Color of the symbol
           vertical = TRUE,   # Vertical mode
           add = TRUE)        # Add it over
```

horizontal box plot

```{r}
# Horizontal box plot
boxplot(df$x, col = "white", horizontal = TRUE)

# Points
stripchart(df$x,              # Data
           method = "jitter", # Random noise
           pch = 19,          # Pch symbol
           col = 4,           # Color of the symbol
           add = TRUE)        # Add it over
```

Box plot by groups

```{r}
# Vertical box plot by group
boxplot(x ~ group, data = df, col = "white")

# Points
stripchart(x ~ group,
           data = df,
           method = "jitter",
           pch = 19,
           col = 2:4,
           vertical = TRUE,
           add = TRUE)
```

### SBBudget expamble

```{r}
library(readxl)
SBBudget_2023 <- read_excel("/Users/ulrike_imac_air/Library/Mobile Documents/com~apple~CloudDocs/Stadt Leipzig/SBBudget/Bewilligungen SBB 2023.xlsx")

SBBudget_2023
```

```{r}
# Vertical box plot by group
# Boxplot
boxplot(betrag ~ stadtbezirksbeirat, data = SBBudget_2023, col = "white")

# Points
stripchart(betrag ~ stadtbezirksbeirat,
           data = SBBudget_2023,
           method = "jitter",
           pch = 19,
           col = my_palette_Blue_Yellow,
           vertical = TRUE,
           add = TRUE)



```

```{r}
# Boxplot
boxplot(betrag ~ stadtbezirksbeirat, data = SBBudget_2023, col = "white", horizontal = TRUE)

# Points
stripchart(betrag ~ stadtbezirksbeirat,
           data = SBBudget_2023,
           method = "jitter",
           pch = 19,
           col = my_palette_Blue_Yellow,
           horizontal = TRUE,
           add = TRUE)
```

```{r}
# Subset data for the group "Mitte"
subset_mitte <- SBBudget_2023[SBBudget_2023$stadtbezirksbeirat == "Mitte", ]

# Boxplot
boxplot(betrag ~ stadtbezirksbeirat, data = subset_mitte, col = "white", horizontal = TRUE)

# Points
stripchart(betrag ~ stadtbezirksbeirat,
           data = subset_mitte,
           method = "jitter",
           pch = 19,
           col = my_palette_Blue_Yellow,
           horizontal = TRUE,
           add = TRUE)

```

```{r}
# Create a new factor variable for combined groups
SBBudget_2023$combined_group <- factor(SBBudget_2023$stadtbezirksbeirat, levels = c("Mitte", "Ost", "West"))

# Subset data for the specified groups
subset_more <- SBBudget_2023[SBBudget_2023$stadtbezirksbeirat %in% c("Mitte", "Ost", "West"), ]

# Boxplot
boxplot(betrag ~ combined_group, data = subset_more, col = "white", horizontal = TRUE)

# Points
stripchart(betrag ~ combined_group,
           data = subset_more,
           method = "jitter",
           pch = 19,
           col = my_palette_Blue_Yellow,
           horizontal = TRUE,
           add = TRUE)


```

```{r}
# Create a new factor variable for combined groups
SBBudget_2023$combined_group <- factor(SBBudget_2023$stadtbezirksbeirat, levels = c("Nordost", "Südost", "Süd"))

# Subset data for the specified groups
subset_more <- SBBudget_2023[SBBudget_2023$stadtbezirksbeirat %in% c("Nordost", "Südost", "Süd"), ]

# Boxplot
boxplot(betrag ~ combined_group, data = subset_more, col = "white", horizontal = TRUE)

# Points
stripchart(betrag ~ combined_group,
           data = subset_more,
           method = "jitter",
           pch = 19,
           col = my_palette_Blue_Yellow,
           add = TRUE)
```

```{r}
# Create a new factor variable for combined groups
SBBudget_2023$combined_group <- factor(SBBudget_2023$stadtbezirksbeirat, levels = c("Südwest", "Alt-West", "Nordwest", "Nord"))

# Subset data for the specified groups
subset_more <- SBBudget_2023[SBBudget_2023$stadtbezirksbeirat %in% c("Südwest", "Alt-West", "Nordwest", "Nord"), ]

# Boxplot
boxplot(betrag ~ combined_group, data = subset_more, col = "white", horizontal = TRUE)

# Points
stripchart(betrag ~ combined_group,
           data = subset_more,
           method = "jitter",
           pch = 19,
           col = my_palette_Blue_Yellow,
           add = TRUE)
```

```{r}
# Create a new factor variable for combined groups
SBBudget_2023$combined_group <- factor(SBBudget_2023$stadtbezirksbeirat, levels = c("Südwest", "Alt-West"))

# Subset data for the specified groups
subset_more <- SBBudget_2023[SBBudget_2023$stadtbezirksbeirat %in% c("Südwest", "Alt-West"), ]

# Boxplot
boxplot(betrag ~ combined_group, data = subset_more, col = "white", horizontal = TRUE)

# Points
stripchart(betrag ~ combined_group,
           data = subset_more,
           method = "jitter",
           pch = 19,
           col = my_palette_Blue_Yellow,
           add = TRUE)
```

```{r}
# Create a new factor variable for combined groups
SBBudget_2023$combined_group <- factor(SBBudget_2023$stadtbezirksbeirat, levels = c("Südost", "Ost"))

# Subset data for the specified groups
subset_more <- SBBudget_2023[SBBudget_2023$stadtbezirksbeirat %in% c("Südost", "Ost"), ]

# Boxplot
boxplot(betrag ~ combined_group, data = subset_more, col = "white", horizontal = TRUE)

# Points
stripchart(betrag ~ combined_group,
           data = subset_more,
           method = "jitter",
           pch = 19,
           col = my_palette_Blue_Yellow,
           add = TRUE)
```

```{r}
# Horizontal box plot
boxplot(SBBudget_2023$betrag, col = "white", horizontal = TRUE)

# Points
stripchart(SBBudget_2023$betrag,              # Data
           method = "jitter", # Random noise
           pch = 19,          # Pch symbol
           col = my_palette_Blue_Yellow,           # Color of the symbol
           add = TRUE)        # Add it over
```

```{r}
library(dplyr)
subset_under_1000 <- SBBudget_2023 %>% 
  filter(betrag <= 1000)

# Horizontal box plot
boxplot(subset_under_1000$betrag, col = "white", horizontal = TRUE)

# Points
stripchart(subset_under_1000$betrag,              
           method = "jitter", 
           pch = 19,         
           col = my_palette_Blue_Yellow,          
           add = TRUE)

    
```

```{r}
subset_over_1000 <- SBBudget_2023 %>% 
  filter(betrag >= 1000)

# Horizontal box plot
boxplot(subset_over_1000$betrag, col = "white", horizontal = TRUE)

# Points
stripchart(subset_over_1000$betrag,              
           method = "jitter", 
           pch = 19,         
           col = my_palette_Blue_Yellow,          
           add = TRUE)
```

#### other methods

-   bin

-   identity

-   stack

-   overplot

```{r}
subset_over_1000 <- SBBudget_2023 %>% 
  filter(betrag >= 1000)

# Horizontal box plot
boxplot(subset_over_1000$betrag, col = "white", horizontal = TRUE)

# Points
stripchart(subset_over_1000$betrag,              
           method = "stack", 
           pch = 19,         
           col = my_palette_Blue_Yellow,          
           add = TRUE)
```
