---
title: "custom_colors"
format: html
editor: visual
---

## Custom_colors

## different themes for different projects

```{r}
install.packages("paletteer")
library(paletteer)
install.packages("wesanderson")
library(wesanderson)
install.packages("ggsci")
library(ggsci)
install.packages("nord")
library(nord)
#install.packages("iWantHue")
#library(iWantHue)
install.packages("colorspace")
library(colorspace)
install.packages("ggthemes")
library(ggthemes)
install.packages("RColorBrewer")
library(RColorBrewer)
install.packages("viridisLite")
library(viridisLite)

```

You can add options to executable code like this

```{r}

my_palette_classic_blue <- paletteer_c("ggthemes::Classic Blue", 30)

my_palette_Harmonic <- paletteer_c("grDevices::Harmonic", 30)

my_palette_Oslo <- paletteer_c("grDevices::Oslo", 30)

my_palette_Blue_Yellow <- paletteer_c("grDevices::Blue-Yellow", 30)

my_palette_Viridis <- paletteer_c("grDevices::Viridis", 30)

my_palette_TealGrn <- paletteer_c("grDevices::TealGrn", 30)

my_palette_ag_GrnYL <- paletteer_c("grDevices::TealGrn", 30)


```

```{r}
my_palette_Blue2DarkRed18Steps <- paletteer_d("colorBlindness::Blue2DarkRed18Steps")

my_palette_BluetoDarkOrange_18 <- paletteer_d("dichromat::BluetoDarkOrange_18")

```

```{r}

my_palette_light_blue_material <- paletteer_d("ggsci::light_blue_material")

my_palette_cyan_material <- paletteer_d("ggsci::cyan_material")

paletteer_d("ggsci::cyan_material")
```

```{r}

my_palette_nuriel_Stone <- paletteer_d("ggthemes::Nuriel_Stone")

```

```{r}

my_palette_dynamic <- paletteer_dynamic("cartography::turquoise.pal", 20)


```

```{r}

my_palette_custom_yellow_blue <- c("lightyellow", "yellow", "#dee767", "#34f5ff", "#299ca2", "darkslategray3","deepskyblue1", "#1531ff", "#2353ff", "#232982")


my_palette_custom_orange_blue <- c("#ff6d2a", "#f86a31", "#f16639", "#ea6340", "#e35f47", "#dc5c4f", "#d55856", "#ce555d", "#c85165", "#c14e6c", "#ba4b73", "#b3477b", "#ac4482", "#a54089", "#9e3d91", "#973998", "#9036a0", "#8932a7", "#822fae", "#7b2bb6", "#7428bd", "#6d25c4", "#6721cc", "#601ed3", "#591ada", "#5217e2", "#4b13e9", "#4410f0", "#3d0cf8", "#3609ff")

my_palette_custom_blues <- c("#34f5ff", "#33eff9", "#32e9f3", "#32e3ec", "#31dde6", "#30d7e0", "#2fd1da", "#2fcbd4", "#2ec6cd", "#2dc0c7", "#2cbac1", "#2cb4bb", "#2baeb5", "#2aa8ae", "#29a2a8", "#299ca2", "#28969c", "#279095", "#268a8f", "#268489", "#257e83", "#24787d", "#237376", "#236d70", "#22676a", "#216164", "#205b5e", "#205557", "#1f4f51", "#1e494b")


my_palette_custom_lightyellow_darkgreen <- c("#fbffae", "#f3f9ab", "#ecf2a7", "#e4eca4", "#dde6a0", "#d5e09d", "#cdd99a", "#c6d396", "#becd93", "#b6c78f", "#afc08c", "#a7ba88", "#a0b485", "#98ad82", "#90a77e", "#89a17b", "#819b77", "#799474", "#728e71", "#6a886d", "#63816a", "#5b7b66", "#537563", "#4c6f5f", "#44685c", "#3c6259", "#355c55", "#2d5652", "#264f4e", "#1e494b")

my_palette_custom_blues01 <- c("#1531ff", "#1631fa", "#1630f6", "#1730f1", "#1730ed", "#182fe8", "#182fe3", "#192fdf", "#192fda", "#1a2ed5", "#1a2ed1", "#1b2ecc", "#1b2dc8", "#1c2dc3", "#1c2dbe", "#1d2cba", "#1d2cb5", "#1e2cb0", "#1e2bac", "#1f2ba7", "#1f2ba3", "#202a9e", "#202a99", "#212a95", "#212a90", "#22298b", "#222987", "#232982", "#23287e", "#242879")


my_palette_custom_all <- c("#34f5ff", "#33eff9", "#32e9f3", "#32e3ec", "#31dde6", "#30d7e0", "#2fd1da", "#2fcbd4", "#2ec6cd", "#2dc0c7", "#2cbac1", "#2cb4bb", "#2baeb5", "#2aa8ae", "#29a2a8", "#299ca2", "#28969c", "#279095", "#268a8f", "#268489", "#257e83", "#24787d", "#237376", "#236d70", "#22676a", "#216164", "#205b5e", "#205557", "#1f4f51", "#1e494b", "#fcff4f", "#f5f955", "#edf35b", "#e6ed61", "#dee767", "#d7e16d", "#cfdb73", "#c8d579", "#c0d080", "#b9ca86", "#b1c48c", "#aabe92", "#a2b898", "#9bb29e", "#93aca4", "#8ca6aa", "#84a0b0", "#7d9ab6", "#7594bc", "#6e8ec2", "#6688c8", "#5f82ce", "#577dd5", "#5077db", "#4871e1", "#416be7", "#3965ed", "#325ff3", "#2a59f9", "#2353ff","#1531ff", "#1631fa", "#1630f6", "#1730f1", "#1730ed", "#182fe8", "#182fe3", "#192fdf", "#192fda", "#1a2ed5", "#1a2ed1", "#1b2ecc", "#1b2dc8", "#1c2dc3", "#1c2dbe", "#1d2cba", "#1d2cb5", "#1e2cb0", "#1e2bac", "#1f2ba7", "#1f2ba3", "#202a9e", "#202a99", "#212a95", "#212a90", "#22298b", "#222987", "#232982", "#23287e", "#242879", "#ff6d2a", "#f86a31", "#f16639", "#ea6340", "#e35f47", "#dc5c4f", "#d55856", "#ce555d", "#c85165", "#c14e6c", "#ba4b73", "#b3477b", "#ac4482", "#a54089", "#9e3d91", "#973998", "#9036a0", "#8932a7", "#822fae", "#7b2bb6", "#7428bd", "#6d25c4", "#6721cc", "#601ed3", "#591ada", "#5217e2", "#4b13e9", "#4410f0", "#3d0cf8", "#3609ff", "#fbffae", "#f3f9ab", "#ecf2a7", "#e4eca4", "#dde6a0", "#d5e09d", "#cdd99a", "#c6d396", "#becd93", "#b6c78f", "#afc08c", "#a7ba88", "#a0b485", "#98ad82", "#90a77e", "#89a17b", "#819b77", "#799474", "#728e71", "#6a886d", "#63816a", "#5b7b66", "#537563", "#4c6f5f", "#44685c", "#3c6259", "#355c55", "#2d5652", "#264f4e", "#1e494b")

my_colors <- c("darkblue", "darkslategray4", "darkslategray2","yellow", "azure3", "aquamarine2", "cornflowerblue", "lightyellow", "cadetblue2","blue1","cyan","deepskyblue1","lightblue","darkgoldenrod", "deepskyblue", "azure1", "aquamarine", "darkgoldenrod1", "cadetblue", "blue2","cyan1", "deepskyblue2", "darkslategray1", "darkgoldenrod2", "azure2", "aquamarine3", "cadetblue3", "blue3", "cyan2", "deepskyblue3", "darkslategray3", "azure", "cyan3", "blue4", "deepskyblue4", "cadetblue4", "lightyellow")

```

```{r}
my_colors5 <- c("yellow", "#deff25", "#44c6b7", "#601ed3", "#190fe4")
my_colors3 <- c("yellow", "#190fe4", "#44c6b7")
```

```{r}
yoga_theme_blue <- c("#4F5361", "#353E55", "#B6F9FF", "#78B1E5", "#5281B4" )

yoga_theme_six <- c("#00CCBB", "#A0DED9", "#FFF9D4", "#FFE5AC", "#FCC868", "#F69F2D")
```

```{r}
boho_purple_theme <- c("#927397", "#D6809c", "#E7CBAE", "#FAF5EF", "#7F7F7F")
```

```{r}
colors_of_the_sea_theme <- c("#e0ece4", "#f7f2e7", "#d8d3cd", "#797a7e", "#3a3b3b")
```

```{r}
power_yoga_theme <- c("#b82677", "#ec7545", "#a9d2cc", "#f4f5f6", "#221f20")
```

```{r}
feminine_theme <- c("#f2aa98", "#fcf1ef", "#bfbfbf", "#f4f4f4", "#00000")
```

```{r}
yoga_in_the_park_theme <- c("#bfae4a", "#e09592", "#f7e6e3", "#e4e4e2", "#474844")
```

```{r}
winter_yoga_theme <- c("#707477", "#b0b1b1", "#dadac3", "#d8ccc1", "#2b2d2f", "#2b3241", "#9ea2ad", "#8b694d", "#e8e2d0", "#b0a18b")
```

```{r}
yin_yoga_theme <- c("#e5babf", "#fcf1ef", "#e7d8c9", "#cdd3d6", "#5e616b")
```

```{r}
youtube_yoga_theme <- c("#e5babf", "#fcf1ef", "#e7d8c9", "#cdd3d6", "#5e616b", "#4F5361", "#353E55", "#B6F9FF", "#78B1E5", "#5281B4", "#bfae4a", "#e09592", "#f7e6e3", "#e4e4e2", "#474844")
```
